### ISSUE TITLE
mypy is missing library stubs

### ISSUE THREAD

**Issue by 0x6e62** [weibullguy/python-lint-plus#8]
Hey there,
when I enable mypy with `use-mypy: true` and use any python library such as PyYAML, I run into errors since mypy can not find the library stubs, raising the following error during exeution:
```
rikai/pattern/parser.py:6: error: Library stubs not installed for "yaml"  [import]
rikai/pattern/parser.py:6: note: Hint: "python3 -m pip install types-PyYAML"
rikai/pattern/parser.py:6: note: (or run "mypy --install-types" to install all missing stub packages)
rikai/pattern/parser.py:6: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
rikai/tests/test_parser.py:2: error: Cannot find implementation or library stub for module named "pytest"  [import]
```

Trying to mitigate this issue by using `extra-mypy-options: "--install-types"` results in a different error, presumly because of a blocked pipe:

```
Running: mypy --install-types rikai
rikai/pattern/parser.py:6: error: Library stubs not installed for "yaml"  [import]
rikai/pattern/parser.py:6: note: Hint: "python3 -m pip install types-PyYAML"
rikai/pattern/parser.py:6: note: (or run "mypy --install-types" to install all missing stub packages)
rikai/pattern/parser.py:6: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
rikai/tests/test_parser.py:2: error: Cannot find implementation or library stub for module named "pytest"  [import]
Traceback (most recent call last):
  File "/github/workspace/python-lint-plus/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/github/workspace/python-lint-plus/lib/python3.10/site-packages/mypy/__main__.py", line 15, in console_entry
    main()
  File "mypy/main.py", line 128, in main
  File "mypy/main.py", line 1[51](https://github.com/dewolf-research/rikai-frontend/actions/runs/4315049610/jobs/7528890235#step:4:52)4, in install_types
EOFError: EOF when reading a line
Found 2 errors in 2 files (checked 17 source files)

Installing missing stub packages:
/github/workspace/python-lint-plus/bin/python3 -m pip install types-PyYAML

Install? [yN] mypy error
```

I'd propose running `mypy --install-types` whenever `use-mypy: true` is set.

Thanks

**Comment by weibullguy** [comment]
@0x6e62 see if v1.12.0 works.

**Comment by 0x6e62** [comment]
Thank you for the quick response, but it seems something with mypy is still amiss

```
Running: mypy rikai
Error: error: Can't determine which types to install with no files to check (and no cache from previous mypy run)
rikai/pattern/parser.py:6: error: Library stubs not installed for "yaml"  [import]
rikai/pattern/parser.py:6: note: Hint: "python3 -m pip install types-PyYAML"
rikai/pattern/parser.py:6: note: (or run "mypy --install-types" to install all missing stub packages)
rikai/pattern/parser.py:6: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
rikai/tests/test_parser.py:2: error: Cannot find implementation or library stub for module named "pytest"  [import]
Found 2 errors in 2 files (checked 17 source files)
mypy error
Error: Process completed with exit code 1.
```

maybe we can work around it by having a way to specify a requirements.txt or something for the virtual environment?

**Comment by 0x6e62** [comment]
I'm sorry it seems all that was needed was the `--non-interactive` flag to allow it to run smoothly
